name: Deploy feature branch

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "event_action=${{ github.event.action }}"
          echo "ref=${{ github.ref }}"
          echo "sha=${{ github.sha }}"
          echo "head_ref=${{ github.head_ref }}"
          echo "base_ref=${{ github.base_ref }}"

  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: ${{ github.head_ref }}
      STACK_NAME: EfaturaAmigoBeStack--${{ github.head_ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::566348719618:role/Github-Actions
          aws-region: eu-west-2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Build Project
        run: yarn build

      - name: CDK Bootstrap
        run: |
          npx cdk bootstrap aws://566348719618/eu-west-2 \
            --trust 566348719618 \
            --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
            --bootstrap-customer-key false

      - name: Deploy CDK Stack
        run: npx cdk deploy EfaturaAmigoBeStack--${DEPLOY_ENV} --require-approval never

  destroy:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: ${{ github.head_ref }}
      STACK_NAME: EfaturaAmigoBeStack--${{ github.head_ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::566348719618:role/Github-Actions
          aws-region: eu-west-2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Build Project
        run: yarn build

      - name: Destroy CDK Stack
        run: npx cdk destroy EfaturaAmigoBeStack--${DEPLOY_ENV} --force

